site_name: Hippocampal replay
nav:
    - Home: index.md
    - Outline: outline.md
    - References: references.md
markdown_extensions:
    - toc:
        permalink: True
        baselevel: 1
        separator: "_"
theme: readthedocs

